language: python

python:
 - "2.7"

install:
 - python setup.py install
 - pip install -r requirements_dev.txt --use-mirrors

script:
 - pep8 component.py
 - coverage run --source=component run_tests.py

after_success:
 - coveralls